FATHER = 'father'
MOTHER = 'mother'
SPOUSE = 'spouse'
SPOUSES = 'spouses'
PARENTS = [FATHER, MOTHER].freeze
VERSION = '0.2.4.13.4'

LEVEL_HEIGHT = 200
COUPLE_SPACING = 140
SIBLING_SPACING = 150

MARKER_ARROW_REF_X = 9
MARKER_ARROW_REF_Y = 3.5
RENDER_OFFSET_X = 50
RENDER_OFFSET_Y = 50

TEXT_NAME_Y_OFFSET = 15
TEXT_DATE_Y_OFFSET = 35
TEXT_ID_Y_OFFSET = 35
TEXT_DATE_BOTH_Y_OFFSET = 30
TEXT_ID_BOTH_Y_OFFSET = 42
